### ISSUE TITLE
[BUG]: when multiple users try to chat with their own documents, the Local Vectra Index will contain the documents from all users

### ISSUE THREAD

**Issue by dannygar** [microsoft/teams-copilot-starter#2]
**Describe the bug**
When multiple users try to chat with their own documents, the Local Vectra Index will contain the documents from all users. This bug is due to the fact that currently, Teams Copilot Starter writes all document indexes into a single common folder (e.g. D:\\Home\\index), which is shared across multiple users.

**To Reproduce**
1. Open the chat with Teams Copilot Starter bot in Teams signed in with the user A.
2. Sign in with the user B, and open the personal chat with Teams Copilot Starter.
3. User A uploads the document A and asks any question on this document.
4. User B uploads the document B and asks any question on this document.

**Expected behavior**
Both users will get the same response, while they were supposed to receive answers to their related uploaded documents.

**Comment by svandenhoven** [comment]
https://github.com/microsoft/teams-copilot-starter/pull/13
